server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://35.78.91.158:3306/free_cloud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: freecloud_user
    password: 1231313Zx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

file:
  storage:
    # Linux server path for file storage
    base-path: /var/lib/freecloud/storage
    # Maximum file size (10GB)
    max-size: 10737418240

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
